const raw = [
// PIPELINES
{id:'travis-ci',name:'Travis CI',web:'https://travis-ci.com',docs:'https://docs.travis-ci.com',
desc:'Pioneering cloud CI/CD platform with native GitHub and Bitbucket integration. YAML-based pipeline configuration, matrix builds across multiple languages and runtimes, parallel testing, and automatic PR deployments. Free for public repositories.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','open-source'],
free:'Free for public repositories. Unlimited builds, unlimited concurrency for open-source. 10,000 build credits/month for private repos.',
paid:'Travis CI — from $69/month for 20K credits, concurrent builds, private repos',pp:69,pm:'usage-based',
bf:4,doc:4,fg:4,se:4,re:3,pe:3,co:3,tb:'maintainer',sd:false,card:false,
rg:true,rc:['IR','KP','SY','CU'],rn:'Available globally with US and EU data centers',la:['en'],at:'CircleCI, GitHub Actions',al:['circleci','github-actions']},

{id:'azure-pipelines',name:'Azure Pipelines',web:'https://azure.microsoft.com/en-us/products/devops/pipelines',docs:'https://learn.microsoft.com/en-us/azure/devops/pipelines',
desc:"Microsoft's cloud CI/CD service with unlimited free minutes for public projects. Supports any language, platform, and cloud. Deep Azure integration, YAML or classic editor pipelines, parallel jobs, and deployment gates.",
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','azure','cloud','container','kubernetes'],
free:'1,800 minutes/month (30 hours) free. 1 parallel job. Unlimited minutes for public projects. 10 free Azure DevOps users. 2 GiB Git storage.',
paid:'Microsoft-hosted — from $40/month for 1 additional parallel job. Self-hosted: unlimited free agents.',pp:40,pm:'subscription',
bf:4,doc:5,fg:4,se:3,re:5,pe:4,co:4,tb:'maintainer',sd:true,sdet:'Free Azure DevOps through Azure for Students ($100 credit, free tier services)',svm:'azure-education',
card:false,rg:true,rc:[],rn:'Available globally with Azure regional data centers',la:['en'],at:'GitHub Actions, CircleCI',al:['github-actions','circleci']},

{id:'bitbucket-pipelines',name:'Bitbucket Pipelines',web:'https://bitbucket.org/product/features/pipelines',docs:'https://support.atlassian.com/bitbucket-cloud/docs/get-started-with-bitbucket-pipelines',
desc:"Atlassian's integrated CI/CD for Bitbucket repositories. YAML-based configuration, Docker-native builds, deploy to any cloud.",
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','docker'],
free:'50 build minutes/month. 1 parallel step. 1 GB artifact storage. Free for up to 5 users in Bitbucket Cloud free plan.',
paid:'Standard — from $3/user/month: 2,500 min, 10 parallel steps. Premium: $6/user/month',pp:3,pm:'per-user',
bf:4,doc:4,fg:2,se:4,re:4,pe:3,co:3,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Available globally with AWS-backed infrastructure',la:['en'],at:'GitHub Actions, GitLab CI/CD',al:['github-actions','gitlab-ci']},

{id:'teamcity',name:'TeamCity',web:'https://www.jetbrains.com/teamcity',docs:'https://www.jetbrains.com/help/teamcity/getting-started.html',
desc:"JetBrains' powerful CI/CD server with intelligent build chains, code coverage, and code inspection. Professional Server free edition supports 3 build agents and 100 build configurations.",
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','self-hosted','free-tier','usage-limits','java','dotnet'],
free:'Professional Server: 3 build agents, 100 build configurations, unlimited builds, all features. Self-hosted only.',
paid:'TeamCity Cloud — from $45/month for 3 agents. Enterprise self-hosted: $1,999/year for 3 agents.',pp:45,pm:'subscription',
bf:3,doc:4,fg:4,se:3,re:4,pe:4,co:3,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Self-hosted: no restrictions. Cloud: available globally',la:['en'],at:'Jenkins, Bamboo',al:['jenkins']},

{id:'drone-ci',name:'Drone CI',web:'https://www.drone.io',docs:'https://docs.drone.io',git:'https://github.com/harness/drone',
desc:'Lightweight cloud-native CI/CD platform built on container technology. Every pipeline step runs in an isolated Docker container. Single-binary architecture, multi-platform support, and deep VCS integration.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','open-source','self-hosted','docker','container','forever-free','saas'],
free:'Open-source: self-hosted, unlimited builds, unlimited repos, unlimited users. Drone Cloud: free for open-source projects.',
paid:'Drone Cloud — from $25/month for private repos. Harness CI — from $0/month for 2 users, 100K CI minutes.',pp:25,pm:'subscription',
bf:3,doc:4,fg:5,se:3,re:3,pe:5,co:3,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Self-hosted: no restrictions. Cloud: global availability',la:['en'],at:'Jenkins, CircleCI',al:['jenkins','circleci']},

{id:'woodpecker-ci',name:'Woodpecker CI',web:'https://woodpecker-ci.org',docs:'https://woodpecker-ci.org/docs/intro',git:'https://github.com/woodpecker-ci/woodpecker',
desc:'Community fork of Drone CI focused on simplicity and reliability. YAML-based pipeline configuration with Docker and Kubernetes runners. Supports GitHub, GitLab, Gitea, and Bitbucket repositories. Completely open-source and self-hostable.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','open-source','self-hosted','docker','kubernetes','forever-free'],
free:'Completely free and open-source. Self-hosted, unlimited builds, unlimited repos, unlimited users.',
paid:null,bf:3,doc:3,fg:5,se:3,re:3,pe:4,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,
rg:true,rc:[],rn:'Self-hosted: no geographic restrictions',la:['en'],at:'Drone CI, Jenkins',al:['drone-ci','jenkins']},

{id:'codefresh',name:'Codefresh',web:'https://codefresh.io',docs:'https://codefresh.io/docs',
desc:'GitOps-powered CI/CD platform designed for Kubernetes and cloud-native applications. Visual pipeline editor, automatic Docker image caching, hybrid runtime, and Argo CD integration.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','kubernetes','docker','gitops'],
free:'3 users, 500 build minutes/month, 1 pipeline, 1 GitOps environment. Includes all pipeline features.',
paid:'Pro — from $34/month: 5 users, 2,500 build minutes, unlimited pipelines',pp:34,pm:'subscription',
bf:4,doc:4,fg:3,se:4,re:4,pe:4,co:3,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Available globally with US and EU regions',la:['en'],at:'CircleCI, GitLab CI/CD',al:['circleci','gitlab-ci']},
];
,
{id:'semaphore-ci',name:'Semaphore CI',web:'https://semaphoreci.com',docs:'https://docs.semaphoreci.com',
desc:'Fast cloud CI/CD platform with 20-second startup times and parallel test execution. YAML-based workflow configuration, native Docker support, Linux and macOS runners, and automatic caching.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','docker'],
free:'1,200 build minutes/month (20 hours). 1 GB cache storage. 1 parallel job. Unlimited projects for public repos.',
paid:'Team — from $14/month: 4,000 minutes, 2 parallel jobs, 5 GB cache',pp:14,pm:'subscription',
bf:4,doc:4,fg:3,se:4,re:4,pe:5,co:3,tb:'maintainer',sd:true,sdet:'Free plan with 1,200 minutes/month sufficient for student projects',svm:'',
card:false,rg:true,rc:[],rn:'Available globally with US and EU data centers',la:['en'],at:'CircleCI, Travis CI',al:['circleci','travis-ci']},

{id:'appveyor',name:'AppVeyor',web:'https://www.appveyor.com',docs:'https://www.appveyor.com/docs',
desc:'CI/CD platform with first-class Windows build support alongside Linux and macOS. Ideal for .NET, C++, and cross-platform projects. YAML configuration, NuGet packaging, and deployment to cloud platforms.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','open-source','dotnet','windows'],
free:'Free for open-source projects: unlimited builds, 1 concurrent job, 60-minute build timeout. Free tier for private repos: 1 project, 14-day build history.',
paid:'Pro — from $39/month: 2 concurrent jobs, unlimited private projects, enhanced support',pp:39,pm:'subscription',
bf:3,doc:3,fg:4,se:3,re:3,pe:3,co:2,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Available globally',la:['en'],at:'Azure Pipelines, CircleCI',al:['azure-pipelines','circleci']},

{id:'cirrus-ci',name:'Cirrus CI',web:'https://cirrus-ci.org',docs:'https://cirrus-ci.org/guide/quick-start',git:'https://github.com/cirruslabs/cirrus-cli',
desc:'Modern cloud CI/CD with native support for Linux, macOS, Windows, and ARM containers. YAML configuration with task-level caching, parallel execution, and built-in Docker/Podman support.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','open-source','docker'],
free:'Free for public repositories: 4,000 compute minutes/month. Linux containers free. macOS and Windows credits: 50/min free per month with per-task limits.',
paid:'From $15/month for additional compute credits, macOS/Windows, and private repository support',pp:15,pm:'usage-based',
bf:3,doc:3,fg:4,se:3,re:3,pe:4,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,
rg:true,rc:[],rn:'Available globally with Google Cloud infrastructure',la:['en'],at:'Travis CI, CircleCI',al:['travis-ci','circleci']},

{id:'codemagic',name:'Codemagic',web:'https://codemagic.io',docs:'https://docs.codemagic.io',
desc:'CI/CD platform specialized for Flutter and mobile app development. Automates building, testing, and publishing to app stores. Pre-configured workflows for Flutter, React Native, and native Android/iOS.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','mobile','flutter','android','ios'],
free:'500 build minutes/month. Unlimited projects. 1 concurrent build. Builds for open-source projects get 1,200 minutes/month.',
paid:'Personal — from $18/month: 2,500 min, 2 concurrent builds. Team: $48/month: 5,000 min, 5 concurrent builds.',pp:18,pm:'subscription',
bf:4,doc:4,fg:3,se:4,re:4,pe:4,co:3,tb:'maintainer',sd:true,sdet:'Free tier adequate for student mobile projects; GitHub Student Pack may include additional credits',svm:'',
card:false,rg:true,rc:[],rn:'Available globally',la:['en'],at:'CircleCI, GitLab CI/CD',al:['circleci','gitlab-ci']},

{id:'gocd',name:'GoCD',web:'https://www.gocd.org',docs:'https://docs.gocd.org',git:'https://github.com/gocd/gocd',
desc:"Open-source CI/CD server by ThoughtWorks with advanced pipeline modeling. Value stream mapping, fan-in/fan-out dependency management, and template-based configuration. Designed for complex deployment pipelines with approval gates and traceability.",
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','open-source','self-hosted','forever-free','java'],
free:'Completely free and open-source. Self-hosted. Unlimited builds, unlimited pipelines, unlimited agents. All features included.',
paid:null,bf:2,doc:4,fg:5,se:2,re:4,pe:3,co:2,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Self-hosted: no restrictions',la:['en'],at:'Jenkins, Spinnaker',al:['jenkins']},

{id:'concourse-ci',name:'Concourse CI',web:'https://concourse-ci.org',docs:'https://concourse-ci.org/docs.html',git:'https://github.com/concourse/concourse',
desc:'Container-centric CI/CD system with a novel pipeline-as-code approach using idempotent resources. Every step runs in a container, pipelines are version-controlled YAML, and the web UI visualizes the full dependency graph.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','open-source','self-hosted','docker','container','forever-free'],
free:'Completely free and open-source. Self-hosted. Unlimited pipelines, unlimited workers. All features included.',
paid:null,bf:2,doc:3,fg:5,se:2,re:4,pe:4,co:3,tb:'community-verified',tbv:'community',sd:false,card:false,
rg:true,rc:[],rn:'Self-hosted: no restrictions',la:['en'],at:'Jenkins, GoCD',al:['jenkins','gocd']},

{id:'harness-ci',name:'Harness CI',web:'https://www.harness.io/products/continuous-integration',docs:'https://developer.harness.io/docs/continuous-integration',
desc:'Next-gen CI platform with AI-powered test intelligence, automatic flaky test detection, and intelligent caching. Cloud-native architecture with Git pipeline abstraction and Kubernetes-native builds.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','kubernetes','ai','enterprise'],
free:'2 users, 100K CI minutes/month (free for personal accounts). 1 concurrent build. Unlimited repos. All features.',
paid:'Team — from $50/month: unlimited users, 8 concurrent builds, enterprise features',pp:50,pm:'subscription',
bf:4,doc:4,fg:5,se:4,re:4,pe:5,co:3,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Available globally with cloud SaaS deployment',la:['en'],at:'CircleCI, GitHub Actions',al:['circleci','github-actions']},

{id:'gitea-actions',name:'Gitea Actions',web:'https://docs.gitea.com/next/usage/actions/overview',docs:'https://docs.gitea.com/next/usage/actions/overview',git:'https://github.com/go-gitea/gitea',
desc:'CI/CD natively integrated into Gitea, compatible with GitHub Actions workflow syntax. Self-hosted, lightweight, and supports the same YAML format as GitHub Actions. Runs in Docker containers with matrix builds.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','open-source','self-hosted','docker','forever-free','git'],
free:'Completely free as part of Gitea. Self-hosted. Unlimited builds, unlimited runners, compatible with all Actions workflow files.',
paid:null,bf:3,doc:3,fg:5,se:3,re:3,pe:3,co:3,tb:'community-verified',tbv:'community',sd:false,card:false,
rg:true,rc:[],rn:'Self-hosted: no restrictions',la:['en'],at:'GitHub Actions, Drone CI',al:['github-actions','drone-ci']},
,
// BUILD AUTOMATION
{id:'rush',name:'Rush',web:'https://rushjs.io',docs:'https://rushjs.io/pages/intro/get_started',git:'https://github.com/microsoft/rushstack',desc:'Microsoft''s scalable monorepo manager for large teams. Intelligent orchestration of npm/pnpm/yarn workspaces with parallel builds, incremental builds, and phased builds.',sub:'build-automation',tags:['ci-cd','automation','devops','open-source','cli','javascript','typescript','nodejs','forever-free'],free:'Completely free and open-source. Unlimited projects. Works with any package manager.',paid:null,bf:2,doc:4,fg:5,se:2,re:4,pe:4,co:3,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'No restrictions (open-source)',la:['en'],at:'Nx, Lerna',al:['nx','lerna']}
,{id:'pants-build',name:'Pants Build',web:'https://www.pantsbuild.org',docs:'https://www.pantsbuild.org/docs',git:'https://github.com/pantsbuild/pants',desc:'Fast, scalable build system for monorepos supporting Python, Java, Scala, Go, shell, and Docker. Fine-grained invalidation, remote caching, and parallel execution.',sub:'build-automation',tags:['ci-cd','automation','devops','open-source','cli','python','java','go','docker','forever-free','self-hosted'],free:'Completely free and open-source. Self-hosted. Unlimited builds.',paid:null,bf:2,doc:3,fg:5,se:2,re:3,pe:4,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'No restrictions',la:['en'],at:'Bazel, Buck2',al:['bazel','buck2']}
,{id:'buck2',name:'Buck2',web:'https://buck2.build',docs:'https://buck2.build/docs',git:'https://github.com/facebook/buck2',desc:"Meta's open-source build system built in Rust. Designed for large-scale monorepos with fine-grained dependency tracking, distributed builds, and remote execution.",sub:'build-automation',tags:['ci-cd','automation','devops','open-source','cli','rust','cpp','python','java','forever-free','high-performance','self-hosted'],free:'Completely free and open-source. Self-hosted. Unlimited builds.',paid:null,bf:1,doc:3,fg:5,se:1,re:4,pe:5,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'No restrictions',la:['en'],at:'Bazel, Pants Build',al:['bazel','pants-build']}
,{id:'meson-build',name:'Meson',web:'https://mesonbuild.com',docs:'https://mesonbuild.com/Manual.html',git:'https://github.com/mesonbuild/meson',desc:'Fast, user-friendly build system designed for speed and developer experience. Python-based configuration language with Ninja as the default backend.',sub:'build-automation',tags:['ci-cd','automation','devops','open-source','cli','python','cpp','rust','forever-free','self-hosted','high-performance'],free:'Completely free and open-source. No usage limits. Cross-platform (Linux, macOS, Windows).',paid:null,bf:3,doc:4,fg:5,se:3,re:4,pe:5,co:3,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions',la:['en'],at:'CMake, GNU Make',al:['cmake','gnu-make']}
,{id:'ninja-build',name:'Ninja',web:'https://ninja-build.org',docs:'https://ninja-build.org/manual.html',git:'https://github.com/ninja-build/ninja',desc:'Blazing-fast small build system focused on speed. Designed as a low-level backend for higher-level build systems like CMake and Meson.',sub:'build-automation',tags:['ci-cd','automation','devops','open-source','cli','cpp','forever-free','self-hosted','high-performance'],free:'Completely free and open-source. No usage limits. Available on all major platforms.',paid:null,bf:2,doc:3,fg:5,se:3,re:5,pe:5,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions',la:['en'],at:'Make, CMake',al:['gnu-make','cmake']}
,{id:'just',name:'Just',web:'https://just.systems',docs:'https://just.systems/man/en',git:'https://github.com/casey/just',desc:"Lightweight command runner alternative to Make. Recipes with parameters, dependencies, and cross-platform shell commands. Single-binary, no dependencies, written in Rust.",sub:'build-automation',tags:['ci-cd','automation','devops','open-source','cli','rust','forever-free','self-hosted'],free:'Completely free and open-source. Single binary, works on all platforms.',paid:null,bf:4,doc:4,fg:5,se:4,re:4,pe:4,co:3,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions',la:['en'],at:'Make, Task',al:['gnu-make']}
,
// TESTING AUTOMATION
{id:'tox',name:'Tox',web:'https://tox.wiki',docs:'https://tox.wiki/en/latest',git:'https://github.com/tox-dev/tox',desc:'Python test environment manager for CI. Automates testing across multiple Python versions and dependency configurations. De facto standard for Python CI testing.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','cli','python','forever-free','self-hosted','qa'],free:'Completely free and open-source. No usage limits. Integrates with any CI platform.',paid:null,bf:3,doc:4,fg:5,se:3,re:4,pe:3,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions (open-source Python tool)',la:['en'],at:'Nox, pyenv',al:['nox']}
,{id:'nox',name:'Nox',web:'https://nox.thea.codes',docs:'https://nox.thea.codes/en/stable',git:'https://github.com/wntrblm/nox',desc:'Flexible Python test session manager inspired by Tox. Standard Python files for configuration instead of INI syntax. Supports parametrized sessions and custom session logic.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','cli','python','forever-free','self-hosted','qa'],free:'Completely free and open-source. No usage limits. Works with any CI/CD system.',paid:null,bf:3,doc:3,fg:5,se:3,re:3,pe:3,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'No restrictions',la:['en'],at:'Tox, pyenv',al:['tox']}
,{id:'testcontainers',name:'Testcontainers',web:'https://testcontainers.com',docs:'https://testcontainers.com/guides',git:'https://github.com/testcontainers',desc:'Library for spinning up disposable Docker containers for integration testing. Provides clean, isolated environments for databases, message brokers, web servers, and more.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','docker','container','integration-test','java','dotnet','python','go','forever-free','self-hosted','qa'],free:'Completely free and open-source. Self-hosted Docker required. No usage limits. All language modules included.',paid:null,bf:3,doc:5,fg:5,se:3,re:4,pe:3,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions (open-source)',la:['en'],at:'Docker Compose, LocalStack',al:[]}
,{id:'act',name:'Act',web:'https://github.com/nektos/act',docs:'https://github.com/nektos/act#readme',git:'https://github.com/nektos/act',desc:'Run GitHub Actions workflows locally. Execute CI pipelines on your machine before pushing, speeding up iteration. Full workflow YAML support, Docker-based job execution.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','cli','docker','github-actions','forever-free','self-hosted','productivity'],free:'Completely free and open-source. No usage limits. Requires Docker. Works on Linux, macOS, and Windows.',paid:null,bf:3,doc:3,fg:5,se:3,re:3,pe:3,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions (open-source)',la:['en'],at:'Docker Compose, GitHub Actions CLI',al:[]}
,{id:'katalon',name:'Katalon Studio',web:'https://katalon.com',docs:'https://docs.katalon.com',desc:'Comprehensive test automation platform supporting web, mobile, API, and desktop testing. Built-in CI/CD integrations with Jenkins, CircleCI, GitHub Actions, and more.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','saas','free-tier','usage-limits','qa','e2e-testing','api'],free:'Free tier: 5 users, 1,000 test runs/month, unlimited test cases, all platform support. Katalon Runtime Engine free for open-source projects.',paid:'Premium — from /month: 10 users, 5K test runs, parallel execution',pp:208,pm:'subscription',bf:4,doc:4,fg:3,se:4,re:3,pe:3,co:3,tb:'maintainer',sd:true,sdet:'Special academic pricing available; Katalon Studio is free for individual learners',svm:'',card:false,rg:true,rc:[],rn:'Available globally',la:['en'],at:'Selenium, Cypress',al:[]}
,{id:'testcafe',name:'TestCafe',web:'https://testcafe.io',docs:'https://testcafe.io/documentation',git:'https://github.com/DevExpress/testcafe',desc:'Node.js end-to-end testing framework that works without WebDriver. Runs on any browser without plugins. Built-in waiting mechanism, parallel test execution, and screenshot/video recording.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','cli','javascript','typescript','e2e-testing','forever-free','self-hosted'],free:'Completely free and open-source. Unlimited tests, unlimited browsers. TestCafe Studio has a free 30-day trial.',paid:'TestCafe Studio — from /month per user for GUI-based test recorder',pp:99,pm:'per-user',bf:4,doc:4,fg:5,se:4,re:3,pe:3,co:3,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions (open-source)',la:['en'],at:'Selenium, Cypress, Playwright',al:[]}
,{id:'selenoid',name:'Selenoid',web:'https://aerokube.com/selenoid',docs:'https://aerokube.com/selenoid/latest',git:'https://github.com/aerokube/selenoid',desc:'Lightweight Selenium Grid implementation using Docker containers. Launches browsers on demand, supports video recording, and provides a live browser UI.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','docker','container','e2e-testing','forever-free','self-hosted','qa'],free:'Completely free and open-source. Self-hosted with Docker. Unlimited browser sessions (limited by available resources).',paid:'Aerokube Moon (cloud version) — from .17/hour for managed browser clusters',pp:0,pm:'usage-based',bf:3,doc:3,fg:5,se:3,re:3,pe:4,co:3,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'Self-hosted: no restrictions',la:['en'],at:'Selenium Grid, Zalenium',al:['zalenium']}
,{id:'zalenium',name:'Zalenium',web:'https://zalenium.github.io',docs:'https://github.com/zalando/zalenium/blob/master/docs/README.md',git:'https://github.com/zalando/zalenium',desc:'Flexible Selenium Grid extension by Zalando. Dynamically scales browsers using Docker, providing on-demand browser containers for testing.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','docker','container','e2e-testing','forever-free','self-hosted'],free:'Completely free and open-source. Self-hosted with Docker Compose. Unlimited scaling based on available resources.',paid:null,bf:3,doc:3,fg:5,se:3,re:3,pe:3,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'Self-hosted: no restrictions',la:['en'],at:'Selenoid, Selenium Grid',al:['selenoid']}
,{id:'junit',name:'JUnit',web:'https://junit.org',docs:'https://junit.org/junit5/docs/current/user-guide',git:'https://github.com/junit-team/junit5',desc:'The foundational unit testing framework for Java. JUnit 5 (Jupiter) with parameterized tests, dynamic tests, test extensions, and powerful assertion APIs. Essential CI component for Java projects.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','java','unit-test','forever-free','self-hosted','qa'],free:'Completely free and open-source. No usage limits. Maven/Gradle plugin available. All features included.',paid:null,bf:4,doc:5,fg:5,se:4,re:5,pe:4,co:5,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions (open-source)',la:['en'],at:'TestNG, Spock',al:[]}
,{id:'cucumber',name:'Cucumber',web:'https://cucumber.io',docs:'https://cucumber.io/docs',git:'https://github.com/cucumber',desc:'BDD (Behavior-Driven Development) testing framework supporting Gherkin syntax. Write human-readable test scenarios that execute as automated tests.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','cli','java','javascript','ruby','python','forever-free','self-hosted','qa'],free:'Completely free and open-source. Cucumber Studio (collaboration) has a free tier: 5 users, 5 repositories.',paid:'Cucumber Studio — from /month for 10 users, unlimited repos',pp:60,pm:'subscription',bf:4,doc:4,fg:4,se:3,re:4,pe:3,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'Open-source: no restrictions. Studio: global SaaS',la:['en'],at:'SpecFlow, Behave',al:[]}
,{id:'robot-framework',name:'Robot Framework',web:'https://robotframework.org',docs:'https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html',git:'https://github.com/robotframework/robotframework',desc:'Keyword-driven test automation framework for acceptance testing and RPA. Human-readable syntax with extensible libraries in Python and Java.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','cli','python','java','rpa','qa','forever-free','self-hosted'],free:'Completely free and open-source. Unlimited tests, libraries, and integrations.',paid:null,bf:3,doc:4,fg:5,se:3,re:4,pe:3,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions (open-source)',la:['en'],at:'Cucumber, Selenium',al:['cucumber']}
,{id:'mockito',name:'Mockito',web:'https://site.mockito.org',docs:'https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html',git:'https://github.com/mockito/mockito',desc:'Most popular Java mocking framework for unit tests. Create mock objects, stub methods, and verify interactions. Clean API with annotations, argument matchers, and BDD-style verification.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','java','unit-test','forever-free','self-hosted','qa'],free:'Completely free and open-source. No usage limits. Works with JUnit 4/5, TestNG, and other test runners.',paid:null,bf:4,doc:4,fg:5,se:4,re:5,pe:4,co:5,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions (open-source)',la:['en'],at:'EasyMock, PowerMock',al:[]}
,{id:'sinon',name:'Sinon.js',web:'https://sinonjs.org',docs:'https://sinonjs.org/releases/latest',git:'https://github.com/sinonjs/sinon',desc:'Standalone test doubles library for JavaScript/Node.js. Spies, stubs, mocks, fake timers, and fake XHR/server. Works with any test framework (Mocha, Jest, Vitest, Jasmine).',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','cli','javascript','typescript','nodejs','unit-test','forever-free','self-hosted','qa'],free:'Completely free and open-source. No usage limits. Works with all major JS test frameworks.',paid:null,bf:3,doc:4,fg:5,se:4,re:4,pe:4,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions (open-source)',la:['en'],at:'Jest mocks, testdouble.js',al:[]}
,{id:'wiremock',name:'WireMock',web:'https://wiremock.org',docs:'https://wiremock.org/docs',git:'https://github.com/wiremock/wiremock',desc:'HTTP mock server for API testing and service virtualization. Stub HTTP responses, verify requests, simulate faults and delays. Standalone server or library for Java, .NET, and Go.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','cli','docker','java','dotnet','go','api','integration-test','forever-free','self-hosted','qa'],free:'Completely free and open-source. Standalone JAR or Docker image. Unlimited stubs and scenarios.',paid:'WireMock Cloud — from /month for 5K requests, 2 team members',pp:0,pm:'usage-based',bf:3,doc:4,fg:5,se:4,re:4,pe:4,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'Self-hosted: no restrictions. Cloud: globally available',la:['en'],at:'MockServer, Mountebank',al:[]}
,{id:'appium',name:'Appium',web:'https://appium.io',docs:'http://appium.io/docs/en/latest',git:'https://github.com/appium/appium',desc:'Cross-platform mobile test automation framework. Automate native, hybrid, and mobile web apps on iOS and Android. WebDriver-compatible protocol, runs on simulators, real devices, or cloud services.',sub:'testing-automation',tags:['ci-cd','automation','testing','devops','open-source','cli','mobile','android','ios','e2e-testing','forever-free','self-hosted','qa'],free:'Completely free and open-source. Self-hosted. Requires device/simulator setup. Unlimited tests.',paid:'Appium Pro (advisory) — commercial support; cloud device providers like Sauce Labs, BrowserStack provide Appium-compatible device clouds',pp:null,pm:'usage-based',bf:2,doc:3,fg:5,se:2,re:3,pe:3,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions (open-source)',la:['en'],at:'Espresso, XCUITest, Detox',al:[]},
// ARTIFACT HOSTING
{id:'sonatype-nexus',name:'Sonatype Nexus Repository',web:'https://www.sonatype.com/products/sonatype-nexus-repository',docs:'https://help.sonatype.com/en/sonatype-nexus-repository.html',desc:'Universal artifact repository manager supporting Maven, npm, Docker, PyPI, NuGet, RubyGems, and 30+ formats. OSS edition is free and self-hosted.',sub:'artifact-hosting',tags:['ci-cd','automation','devops','self-hosted','free-tier','java','docker','forever-free','package-manager'],free:'Nexus Repository OSS: free and self-hosted. Supports Maven, npm, Docker, PyPI, NuGet, RubyGems, Git LFS, APT, YUM, raw, and more.',paid:'Nexus Pro — from ,000/year: SAML/SSO, HA clustering, Form-based formats',pp:12000,pm:'subscription',bf:3,doc:4,fg:5,se:3,re:4,pe:4,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'Self-hosted: no restrictions',la:['en'],at:'JFrog Artifactory, CloudRepo',al:['jfrog-artifactory']}
,{id:'jfrog-artifactory',name:'JFrog Artifactory',web:'https://jfrog.com/artifactory',docs:'https://jfrog.com/help/r/jfrog-artifactory-documentation',desc:'Universal artifact repository manager with enterprise-grade features. Supports all major package formats, Docker registries, Helm charts, and generic repositories.',sub:'artifact-hosting',tags:['ci-cd','automation','devops','self-hosted','free-tier','usage-limits','docker','java','package-manager','container'],free:'Artifactory OSS: free self-hosted (Maven, Ivy, Gradle, Docker, generic). JFrog Cloud Free Tier: 2 GB storage, 2 users, 100 CI integrations.',paid:'Pro — from /year: unlimited storage, 5 users, HA, Xray integration',pp:989,pm:'subscription',bf:3,doc:5,fg:3,se:3,re:5,pe:4,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'Self-hosted: no restrictions. Cloud: global availability',la:['en'],at:'Sonatype Nexus, Harbor',al:['sonatype-nexus']}
,{id:'docker-hub',name:'Docker Hub',web:'https://hub.docker.com',docs:'https://docs.docker.com/docker-hub',desc:"World's largest container image registry and community. Host and share Docker images with automated builds from GitHub/Bitbucket. Official images for popular software.",sub:'artifact-hosting',tags:['ci-cd','automation','devops','saas','free-tier','usage-limits','docker','container','rate-limited'],free:'1 private repository. Unlimited public repositories. 200 pulls/6 hours (unauthenticated), 100 pulls/6 hours (authenticated free).',paid:'Pro — from /month: unlimited private repos, 300 pulls/6 hours, 5 concurrent builds',pp:5,pm:'subscription',bf:5,doc:4,fg:3,se:5,re:4,pe:3,co:5,tb:'maintainer',sd:true,sdet:'Docker Pro free for verified students via GitHub Student Developer Pack',svm:'github-education',card:false,rg:true,rc:[],rn:'Available globally; Docker Hub is US-based',la:['en'],at:'GitHub Container Registry, Quay.io',al:['ghcr','quay-io']}
,{id:'ghcr',name:'GitHub Container Registry',web:'https://ghcr.io',docs:'https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry',desc:'Docker container registry integrated into GitHub Packages. Store and publish OCI-compatible container images alongside your source code. Free for public images.',sub:'artifact-hosting',tags:['ci-cd','automation','devops','saas','free-tier','docker','container','github','forever-free'],free:'Free for public images. Private images: 500 MB free storage, 1 GB free data transfer/month for private repos.',paid:'Part of GitHub paid plans or billed per usage: .25/GB storage, .50/GB transfer',pp:0,pm:'usage-based',bf:4,doc:4,fg:4,se:5,re:5,pe:4,co:4,tb:'maintainer',sd:true,sdet:'GitHub Student Pack includes free GitHub Team plan with increased storage/transfer limits',svm:'github-education',card:false,rg:true,rc:['IR','KP','SY','CU'],rn:'Available globally with US, EU, and APAC regions',la:['en'],at:'Docker Hub, Quay.io',al:['docker-hub','quay-io']}
,{id:'harbor',name:'Harbor',web:'https://goharbor.io',docs:'https://goharbor.io/docs',git:'https://github.com/goharbor/harbor',desc:'Open-source cloud-native container registry with built-in security scanning. Role-based access control, image replication across registries, vulnerability scanning via Trivy. CNCF graduated project.',sub:'artifact-hosting',tags:['ci-cd','automation','devops','open-source','self-hosted','docker','container','security','forever-free','kubernetes'],free:'Completely free and open-source. Self-hosted. Unlimited images, users, and projects. Includes vulnerability scanning, replication, and RBAC.',paid:null,bf:3,doc:4,fg:5,se:3,re:4,pe:4,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions (self-hosted open-source)',la:['en'],at:'Quay.io, Docker Registry',al:['quay-io']}
,{id:'quay-io',name:'Quay.io',web:'https://quay.io',docs:'https://docs.quay.io',desc:"Red Hat's enterprise container registry with automated builds, vulnerability scanning, and geo-replication. Supports Docker images, OCI artifacts, and AppC images.",sub:'artifact-hosting',tags:['ci-cd','automation','devops','saas','free-tier','usage-limits','docker','container','kubernetes'],free:'Unlimited public repositories. 1 private repository. Unlimited public automated builds. Vulnerability scanning included.',paid:'Starter — /month: 5 private repos. Pro — /month: unlimited private repos',pp:10,pm:'subscription',bf:4,doc:3,fg:4,se:4,re:4,pe:4,co:3,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'Available globally with US and EU regions',la:['en'],at:'Docker Hub, GitHub Container Registry',al:['docker-hub','ghcr']}
,{id:'cloudsmith',name:'Cloudsmith',web:'https://cloudsmith.io',docs:'https://help.cloudsmith.io/docs',desc:'Cloud-native artifact management platform supporting 30+ package formats. Host and proxy containers, packages, and binaries with built-in vulnerability scanning.',sub:'artifact-hosting',tags:['ci-cd','automation','devops','saas','free-tier','usage-limits','docker','container','package-manager','security'],free:'1 GB storage, 1 GB transfer/month. Unlimited public repositories. 5 team members. Vulnerability scanning included.',paid:'Pro — from /month: 50 GB storage, 50 GB transfer, unlimited members',pp:99,pm:'subscription',bf:4,doc:4,fg:3,se:4,re:4,pe:4,co:3,tb:'maintainer',sd:true,sdet:'Free tier sufficient for student projects; academic discounts available',svm:'',card:false,rg:true,rc:[],rn:'Available globally with multiple storage regions',la:['en'],at:'Sonatype Nexus, JFrog Artifactory',al:['sonatype-nexus','jfrog-artifactory']}
,{id:'packagecloud',name:'PackageCloud',web:'https://packagecloud.io',docs:'https://docs.packagecloud.io',desc:'Hosted package repository for Debian, RPM, RubyGems, Python, Node.js, Java, and more. Private and public repos with team collaboration and CI/CD integration.',sub:'artifact-hosting',tags:['ci-cd','automation','devops','saas','free-tier','usage-limits','package-manager','open-source'],free:'1 private repository, unlimited public repositories. 200 MB storage. 1 GB transfer/month. 2 team members.',paid:'Personal — /month: 10GB storage, 10GB transfer, 5 users. Team — /month',pp:15,pm:'subscription',bf:4,doc:3,fg:3,se:4,re:4,pe:3,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'Available globally',la:['en'],at:'Gemfury, Cloudsmith',al:['gemfury','cloudsmith']}
,{id:'gemfury',name:'Gemfury',web:'https://gemfury.com',docs:'https://gemfury.com/help',desc:'Hosted package registry for RubyGems, npm, PyPI, Maven, NuGet, PHP Composer, and Debian packages. Private package hosting with webhook CI integration.',sub:'artifact-hosting',tags:['ci-cd','automation','devops','saas','free-tier','usage-limits','package-manager'],free:'1 private repository, unlimited public. 100 MB storage. 1 collaborator. 2,500 package downloads/month.',paid:'Pro — from /month: 1GB storage, unlimited collaborators, 5 repos',pp:15,pm:'subscription',bf:4,doc:3,fg:2,se:4,re:3,pe:3,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'Available globally',la:['en'],at:'PackageCloud, Cloudsmith',al:['packagecloud','cloudsmith']}
,{id:'proget',name:'ProGet',web:'https://inedo.com/proget',docs:'https://docs.inedo.com/docs/proget/overview',desc:'Universal package manager by Inedo. Host and proxy NuGet, npm, Docker, Maven, RubyGems, PyPI, and Chocolatey packages. Built-in vulnerability scanning and license compliance.',sub:'artifact-hosting',tags:['ci-cd','automation','devops','self-hosted','free-tier','usage-limits','docker','package-manager','dotnet'],free:'ProGet Free: 1 feed, unlimited packages/users, 1 connector. Self-hosted on Windows/Linux.',paid:'Pro — from ,995/year: unlimited feeds, 20+ connectors, vulnerability scanning',pp:3995,pm:'subscription',bf:3,doc:4,fg:4,se:3,re:4,pe:4,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'Self-hosted: no restrictions',la:['en'],at:'Sonatype Nexus, JFrog Artifactory',al:['sonatype-nexus','jfrog-artifactory']}
,{id:'jitpack',name:'JitPack',web:'https://jitpack.io',docs:'https://jitpack.io/docs',desc:'On-demand package repository for JVM and Android libraries. Builds artifacts directly from GitHub repositories on the fly. Supports Maven, Gradle, sbt, and Leiningen.',sub:'artifact-hosting',tags:['ci-cd','automation','devops','saas','free-tier','java','android','gradle','maven','git','forever-free'],free:'Free for public GitHub repositories. Unlimited builds and storage. No account required for consuming public artifacts.',paid:'JitPack Enterprise — from /month: private repos, priority support, custom domain',pp:99,pm:'subscription',bf:4,doc:3,fg:5,se:5,re:4,pe:3,co:3,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'Available globally',la:['en'],at:'Maven Central, Sonatype Nexus',al:['sonatype-nexus']}
,{id:'chartmuseum',name:'ChartMuseum',web:'https://chartmuseum.com',docs:'https://chartmuseum.com/docs',git:'https://github.com/helm/chartmuseum',desc:'Open-source Helm Chart repository server. Store, manage, and distribute Kubernetes Helm charts. Supports cloud storage backends (S3, GCS, Azure Blob, OSS). CNCF project.',sub:'artifact-hosting',tags:['ci-cd','automation','devops','open-source','self-hosted','docker','kubernetes','helm','forever-free','container'],free:'Completely free and open-source. Self-hosted. Unlimited charts and versions. Multiple storage backends supported.',paid:null,bf:3,doc:3,fg:5,se:3,re:3,pe:3,co:3,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'Self-hosted: no restrictions',la:['en'],at:'Harbor (Helm Charts), Quay.io (App Registry)',al:['harbor']}
,{id:'minio',name:'MinIO',web:'https://min.io',docs:'https://min.io/docs/minio/container/index.html',git:'https://github.com/minio/minio',desc:'High-performance, S3-compatible object storage server. Perfect for artifact storage in CI/CD pipelines. Supports multi-cloud replication, erasure coding, and bucket versioning.',sub:'artifact-hosting',tags:['ci-cd','automation','devops','open-source','self-hosted','docker','kubernetes','s3-compatible','storage','forever-free','high-performance'],free:'Completely free and open-source. Self-hosted. Unlimited storage (hardware-dependent). S3-compatible API.',paid:'MinIO Enterprise — from /instance/month: SUBNET support, security advisory, performance',pp:10,pm:'subscription',bf:3,doc:5,fg:5,se:3,re:5,pe:5,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'Self-hosted: no restrictions',la:['en'],at:'AWS S3, LocalStack',al:[]}
,{id:'cloudrepo',name:'CloudRepo',web:'https://cloudrepo.io',docs:'https://docs.cloudrepo.io',desc:'Hosted private Maven and PyPI repository. Secure artifact storage with access controls, team management, and audit logging. No infrastructure to manage.',sub:'artifact-hosting',tags:['ci-cd','automation','devops','saas','free-tier','usage-limits','java','python','package-manager'],free:'250 MB storage. 1 GB bandwidth/month. Unlimited repos. 3 users. Maven and PyPI support.',paid:'Team — from /month: 5 GB storage, 25 GB bandwidth, 25 users',pp:25,pm:'subscription',bf:4,doc:3,fg:2,se:4,re:3,pe:3,co:1,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'Available globally',la:['en'],at:'Sonatype Nexus, JFrog Artifactory',al:['sonatype-nexus','jfrog-artifactory']}
,{id:'myget',name:'MyGet',web:'https://www.myget.org',docs:'https://docs.myget.org',desc:'Hosted package registry supporting NuGet, npm, Maven, Bower, VSIX, and more. CI/CD integration with GitHub, Azure DevOps, and Bitbucket.',sub:'artifact-hosting',tags:['ci-cd','automation','devops','saas','free-tier','usage-limits','dotnet','package-manager'],free:'1 private feed, unlimited public feeds. 500 MB storage. 2 team members. 1 upstream source.',paid:'Pro — from /month: 10 private feeds, 5 GB storage, 25 team members',pp:29,pm:'subscription',bf:4,doc:3,fg:2,se:4,re:3,pe:3,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'Available globally',la:['en'],at:'ProGet, NuGet Gallery',al:['proget']},
