const raw = [
// PIPELINES
{id:'travis-ci',name:'Travis CI',web:'https://travis-ci.com',docs:'https://docs.travis-ci.com',
desc:'Pioneering cloud CI/CD platform with native GitHub and Bitbucket integration. YAML-based pipeline configuration, matrix builds across multiple languages and runtimes, parallel testing, and automatic PR deployments. Free for public repositories.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','open-source'],
free:'Free for public repositories. Unlimited builds, unlimited concurrency for open-source. 10,000 build credits/month for private repos.',
paid:'Travis CI — from $69/month for 20K credits, concurrent builds, private repos',pp:69,pm:'usage-based',
bf:4,doc:4,fg:4,se:4,re:3,pe:3,co:3,tb:'maintainer',sd:false,card:false,
rg:true,rc:['IR','KP','SY','CU'],rn:'Available globally with US and EU data centers',la:['en'],at:'CircleCI, GitHub Actions',al:['circleci','github-actions']},

{id:'azure-pipelines',name:'Azure Pipelines',web:'https://azure.microsoft.com/en-us/products/devops/pipelines',docs:'https://learn.microsoft.com/en-us/azure/devops/pipelines',
desc:"Microsoft's cloud CI/CD service with unlimited free minutes for public projects. Supports any language, platform, and cloud. Deep Azure integration, YAML or classic editor pipelines, parallel jobs, and deployment gates.",
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','azure','cloud','container','kubernetes'],
free:'1,800 minutes/month (30 hours) free. 1 parallel job. Unlimited minutes for public projects. 10 free Azure DevOps users. 2 GiB Git storage.',
paid:'Microsoft-hosted — from $40/month for 1 additional parallel job. Self-hosted: unlimited free agents.',pp:40,pm:'subscription',
bf:4,doc:5,fg:4,se:3,re:5,pe:4,co:4,tb:'maintainer',sd:true,sdet:'Free Azure DevOps through Azure for Students ($100 credit, free tier services)',svm:'azure-education',
card:false,rg:true,rc:[],rn:'Available globally with Azure regional data centers',la:['en'],at:'GitHub Actions, CircleCI',al:['github-actions','circleci']},

{id:'bitbucket-pipelines',name:'Bitbucket Pipelines',web:'https://bitbucket.org/product/features/pipelines',docs:'https://support.atlassian.com/bitbucket-cloud/docs/get-started-with-bitbucket-pipelines',
desc:"Atlassian's integrated CI/CD for Bitbucket repositories. YAML-based configuration, Docker-native builds, deploy to any cloud.",
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','docker'],
free:'50 build minutes/month. 1 parallel step. 1 GB artifact storage. Free for up to 5 users in Bitbucket Cloud free plan.',
paid:'Standard — from $3/user/month: 2,500 min, 10 parallel steps. Premium: $6/user/month',pp:3,pm:'per-user',
bf:4,doc:4,fg:2,se:4,re:4,pe:3,co:3,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Available globally with AWS-backed infrastructure',la:['en'],at:'GitHub Actions, GitLab CI/CD',al:['github-actions','gitlab-ci']},

{id:'teamcity',name:'TeamCity',web:'https://www.jetbrains.com/teamcity',docs:'https://www.jetbrains.com/help/teamcity/getting-started.html',
desc:"JetBrains' powerful CI/CD server with intelligent build chains, code coverage, and code inspection. Professional Server free edition supports 3 build agents and 100 build configurations.",
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','self-hosted','free-tier','usage-limits','java','dotnet'],
free:'Professional Server: 3 build agents, 100 build configurations, unlimited builds, all features. Self-hosted only.',
paid:'TeamCity Cloud — from $45/month for 3 agents. Enterprise self-hosted: $1,999/year for 3 agents.',pp:45,pm:'subscription',
bf:3,doc:4,fg:4,se:3,re:4,pe:4,co:3,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Self-hosted: no restrictions. Cloud: available globally',la:['en'],at:'Jenkins, Bamboo',al:['jenkins']},

{id:'drone-ci',name:'Drone CI',web:'https://www.drone.io',docs:'https://docs.drone.io',git:'https://github.com/harness/drone',
desc:'Lightweight cloud-native CI/CD platform built on container technology. Every pipeline step runs in an isolated Docker container. Single-binary architecture, multi-platform support, and deep VCS integration.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','open-source','self-hosted','docker','container','forever-free','saas'],
free:'Open-source: self-hosted, unlimited builds, unlimited repos, unlimited users. Drone Cloud: free for open-source projects.',
paid:'Drone Cloud — from $25/month for private repos. Harness CI — from $0/month for 2 users, 100K CI minutes.',pp:25,pm:'subscription',
bf:3,doc:4,fg:5,se:3,re:3,pe:5,co:3,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Self-hosted: no restrictions. Cloud: global availability',la:['en'],at:'Jenkins, CircleCI',al:['jenkins','circleci']},

{id:'woodpecker-ci',name:'Woodpecker CI',web:'https://woodpecker-ci.org',docs:'https://woodpecker-ci.org/docs/intro',git:'https://github.com/woodpecker-ci/woodpecker',
desc:'Community fork of Drone CI focused on simplicity and reliability. YAML-based pipeline configuration with Docker and Kubernetes runners. Supports GitHub, GitLab, Gitea, and Bitbucket repositories. Completely open-source and self-hostable.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','open-source','self-hosted','docker','kubernetes','forever-free'],
free:'Completely free and open-source. Self-hosted, unlimited builds, unlimited repos, unlimited users.',
paid:null,bf:3,doc:3,fg:5,se:3,re:3,pe:4,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,
rg:true,rc:[],rn:'Self-hosted: no geographic restrictions',la:['en'],at:'Drone CI, Jenkins',al:['drone-ci','jenkins']},

{id:'codefresh',name:'Codefresh',web:'https://codefresh.io',docs:'https://codefresh.io/docs',
desc:'GitOps-powered CI/CD platform designed for Kubernetes and cloud-native applications. Visual pipeline editor, automatic Docker image caching, hybrid runtime, and Argo CD integration.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','kubernetes','docker','gitops'],
free:'3 users, 500 build minutes/month, 1 pipeline, 1 GitOps environment. Includes all pipeline features.',
paid:'Pro — from $34/month: 5 users, 2,500 build minutes, unlimited pipelines',pp:34,pm:'subscription',
bf:4,doc:4,fg:3,se:4,re:4,pe:4,co:3,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Available globally with US and EU regions',la:['en'],at:'CircleCI, GitLab CI/CD',al:['circleci','gitlab-ci']},
];
,
{id:'semaphore-ci',name:'Semaphore CI',web:'https://semaphoreci.com',docs:'https://docs.semaphoreci.com',
desc:'Fast cloud CI/CD platform with 20-second startup times and parallel test execution. YAML-based workflow configuration, native Docker support, Linux and macOS runners, and automatic caching.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','docker'],
free:'1,200 build minutes/month (20 hours). 1 GB cache storage. 1 parallel job. Unlimited projects for public repos.',
paid:'Team — from $14/month: 4,000 minutes, 2 parallel jobs, 5 GB cache',pp:14,pm:'subscription',
bf:4,doc:4,fg:3,se:4,re:4,pe:5,co:3,tb:'maintainer',sd:true,sdet:'Free plan with 1,200 minutes/month sufficient for student projects',svm:'',
card:false,rg:true,rc:[],rn:'Available globally with US and EU data centers',la:['en'],at:'CircleCI, Travis CI',al:['circleci','travis-ci']},

{id:'appveyor',name:'AppVeyor',web:'https://www.appveyor.com',docs:'https://www.appveyor.com/docs',
desc:'CI/CD platform with first-class Windows build support alongside Linux and macOS. Ideal for .NET, C++, and cross-platform projects. YAML configuration, NuGet packaging, and deployment to cloud platforms.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','open-source','dotnet','windows'],
free:'Free for open-source projects: unlimited builds, 1 concurrent job, 60-minute build timeout. Free tier for private repos: 1 project, 14-day build history.',
paid:'Pro — from $39/month: 2 concurrent jobs, unlimited private projects, enhanced support',pp:39,pm:'subscription',
bf:3,doc:3,fg:4,se:3,re:3,pe:3,co:2,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Available globally',la:['en'],at:'Azure Pipelines, CircleCI',al:['azure-pipelines','circleci']},

{id:'cirrus-ci',name:'Cirrus CI',web:'https://cirrus-ci.org',docs:'https://cirrus-ci.org/guide/quick-start',git:'https://github.com/cirruslabs/cirrus-cli',
desc:'Modern cloud CI/CD with native support for Linux, macOS, Windows, and ARM containers. YAML configuration with task-level caching, parallel execution, and built-in Docker/Podman support.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','open-source','docker'],
free:'Free for public repositories: 4,000 compute minutes/month. Linux containers free. macOS and Windows credits: 50/min free per month with per-task limits.',
paid:'From $15/month for additional compute credits, macOS/Windows, and private repository support',pp:15,pm:'usage-based',
bf:3,doc:3,fg:4,se:3,re:3,pe:4,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,
rg:true,rc:[],rn:'Available globally with Google Cloud infrastructure',la:['en'],at:'Travis CI, CircleCI',al:['travis-ci','circleci']},

{id:'codemagic',name:'Codemagic',web:'https://codemagic.io',docs:'https://docs.codemagic.io',
desc:'CI/CD platform specialized for Flutter and mobile app development. Automates building, testing, and publishing to app stores. Pre-configured workflows for Flutter, React Native, and native Android/iOS.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','mobile','flutter','android','ios'],
free:'500 build minutes/month. Unlimited projects. 1 concurrent build. Builds for open-source projects get 1,200 minutes/month.',
paid:'Personal — from $18/month: 2,500 min, 2 concurrent builds. Team: $48/month: 5,000 min, 5 concurrent builds.',pp:18,pm:'subscription',
bf:4,doc:4,fg:3,se:4,re:4,pe:4,co:3,tb:'maintainer',sd:true,sdet:'Free tier adequate for student mobile projects; GitHub Student Pack may include additional credits',svm:'',
card:false,rg:true,rc:[],rn:'Available globally',la:['en'],at:'CircleCI, GitLab CI/CD',al:['circleci','gitlab-ci']},

{id:'gocd',name:'GoCD',web:'https://www.gocd.org',docs:'https://docs.gocd.org',git:'https://github.com/gocd/gocd',
desc:"Open-source CI/CD server by ThoughtWorks with advanced pipeline modeling. Value stream mapping, fan-in/fan-out dependency management, and template-based configuration. Designed for complex deployment pipelines with approval gates and traceability.",
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','open-source','self-hosted','forever-free','java'],
free:'Completely free and open-source. Self-hosted. Unlimited builds, unlimited pipelines, unlimited agents. All features included.',
paid:null,bf:2,doc:4,fg:5,se:2,re:4,pe:3,co:2,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Self-hosted: no restrictions',la:['en'],at:'Jenkins, Spinnaker',al:['jenkins']},

{id:'concourse-ci',name:'Concourse CI',web:'https://concourse-ci.org',docs:'https://concourse-ci.org/docs.html',git:'https://github.com/concourse/concourse',
desc:'Container-centric CI/CD system with a novel pipeline-as-code approach using idempotent resources. Every step runs in a container, pipelines are version-controlled YAML, and the web UI visualizes the full dependency graph.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','open-source','self-hosted','docker','container','forever-free'],
free:'Completely free and open-source. Self-hosted. Unlimited pipelines, unlimited workers. All features included.',
paid:null,bf:2,doc:3,fg:5,se:2,re:4,pe:4,co:3,tb:'community-verified',tbv:'community',sd:false,card:false,
rg:true,rc:[],rn:'Self-hosted: no restrictions',la:['en'],at:'Jenkins, GoCD',al:['jenkins','gocd']},

{id:'harness-ci',name:'Harness CI',web:'https://www.harness.io/products/continuous-integration',docs:'https://developer.harness.io/docs/continuous-integration',
desc:'Next-gen CI platform with AI-powered test intelligence, automatic flaky test detection, and intelligent caching. Cloud-native architecture with Git pipeline abstraction and Kubernetes-native builds.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','saas','free-tier','usage-limits','kubernetes','ai','enterprise'],
free:'2 users, 100K CI minutes/month (free for personal accounts). 1 concurrent build. Unlimited repos. All features.',
paid:'Team — from $50/month: unlimited users, 8 concurrent builds, enterprise features',pp:50,pm:'subscription',
bf:4,doc:4,fg:5,se:4,re:4,pe:5,co:3,tb:'maintainer',sd:false,card:false,
rg:true,rc:[],rn:'Available globally with cloud SaaS deployment',la:['en'],at:'CircleCI, GitHub Actions',al:['circleci','github-actions']},

{id:'gitea-actions',name:'Gitea Actions',web:'https://docs.gitea.com/next/usage/actions/overview',docs:'https://docs.gitea.com/next/usage/actions/overview',git:'https://github.com/go-gitea/gitea',
desc:'CI/CD natively integrated into Gitea, compatible with GitHub Actions workflow syntax. Self-hosted, lightweight, and supports the same YAML format as GitHub Actions. Runs in Docker containers with matrix builds.',
sub:'pipelines',tags:['ci-cd','pipelines','automation','devops','open-source','self-hosted','docker','forever-free','git'],
free:'Completely free as part of Gitea. Self-hosted. Unlimited builds, unlimited runners, compatible with all Actions workflow files.',
paid:null,bf:3,doc:3,fg:5,se:3,re:3,pe:3,co:3,tb:'community-verified',tbv:'community',sd:false,card:false,
rg:true,rc:[],rn:'Self-hosted: no restrictions',la:['en'],at:'GitHub Actions, Drone CI',al:['github-actions','drone-ci']},
,
// BUILD AUTOMATION
{id:'rush',name:'Rush',web:'https://rushjs.io',docs:'https://rushjs.io/pages/intro/get_started',git:'https://github.com/microsoft/rushstack',desc:'Microsoft''s scalable monorepo manager for large teams. Intelligent orchestration of npm/pnpm/yarn workspaces with parallel builds, incremental builds, and phased builds.',sub:'build-automation',tags:['ci-cd','automation','devops','open-source','cli','javascript','typescript','nodejs','forever-free'],free:'Completely free and open-source. Unlimited projects. Works with any package manager.',paid:null,bf:2,doc:4,fg:5,se:2,re:4,pe:4,co:3,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'No restrictions (open-source)',la:['en'],at:'Nx, Lerna',al:['nx','lerna']}
,{id:'pants-build',name:'Pants Build',web:'https://www.pantsbuild.org',docs:'https://www.pantsbuild.org/docs',git:'https://github.com/pantsbuild/pants',desc:'Fast, scalable build system for monorepos supporting Python, Java, Scala, Go, shell, and Docker. Fine-grained invalidation, remote caching, and parallel execution.',sub:'build-automation',tags:['ci-cd','automation','devops','open-source','cli','python','java','go','docker','forever-free','self-hosted'],free:'Completely free and open-source. Self-hosted. Unlimited builds.',paid:null,bf:2,doc:3,fg:5,se:2,re:3,pe:4,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'No restrictions',la:['en'],at:'Bazel, Buck2',al:['bazel','buck2']}
,{id:'buck2',name:'Buck2',web:'https://buck2.build',docs:'https://buck2.build/docs',git:'https://github.com/facebook/buck2',desc:"Meta's open-source build system built in Rust. Designed for large-scale monorepos with fine-grained dependency tracking, distributed builds, and remote execution.",sub:'build-automation',tags:['ci-cd','automation','devops','open-source','cli','rust','cpp','python','java','forever-free','high-performance','self-hosted'],free:'Completely free and open-source. Self-hosted. Unlimited builds.',paid:null,bf:1,doc:3,fg:5,se:1,re:4,pe:5,co:2,tb:'community-verified',tbv:'community',sd:false,card:false,rg:true,rc:[],rn:'No restrictions',la:['en'],at:'Bazel, Pants Build',al:['bazel','pants-build']}
,{id:'meson-build',name:'Meson',web:'https://mesonbuild.com',docs:'https://mesonbuild.com/Manual.html',git:'https://github.com/mesonbuild/meson',desc:'Fast, user-friendly build system designed for speed and developer experience. Python-based configuration language with Ninja as the default backend.',sub:'build-automation',tags:['ci-cd','automation','devops','open-source','cli','python','cpp','rust','forever-free','self-hosted','high-performance'],free:'Completely free and open-source. No usage limits. Cross-platform (Linux, macOS, Windows).',paid:null,bf:3,doc:4,fg:5,se:3,re:4,pe:5,co:3,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions',la:['en'],at:'CMake, GNU Make',al:['cmake','gnu-make']}
,{id:'ninja-build',name:'Ninja',web:'https://ninja-build.org',docs:'https://ninja-build.org/manual.html',git:'https://github.com/ninja-build/ninja',desc:'Blazing-fast small build system focused on speed. Designed as a low-level backend for higher-level build systems like CMake and Meson.',sub:'build-automation',tags:['ci-cd','automation','devops','open-source','cli','cpp','forever-free','self-hosted','high-performance'],free:'Completely free and open-source. No usage limits. Available on all major platforms.',paid:null,bf:2,doc:3,fg:5,se:3,re:5,pe:5,co:4,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions',la:['en'],at:'Make, CMake',al:['gnu-make','cmake']}
,{id:'just',name:'Just',web:'https://just.systems',docs:'https://just.systems/man/en',git:'https://github.com/casey/just',desc:"Lightweight command runner alternative to Make. Recipes with parameters, dependencies, and cross-platform shell commands. Single-binary, no dependencies, written in Rust.",sub:'build-automation',tags:['ci-cd','automation','devops','open-source','cli','rust','forever-free','self-hosted'],free:'Completely free and open-source. Single binary, works on all platforms.',paid:null,bf:4,doc:4,fg:5,se:4,re:4,pe:4,co:3,tb:'maintainer',sd:false,card:false,rg:true,rc:[],rn:'No restrictions',la:['en'],at:'Make, Task',al:['gnu-make']}
